name: Aufgabe2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout Rep
        uses: actions/checkout@v4
      - name: setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: test
        run: mvn -B clean verify
      - name: upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/

  lint:
    runs-on: ubuntu-latest
    if: always()
    env:
      Test: test
    strategy: 
      matrix:
        version: ['11', '17', '21']
    steps:
      - name: checkout Rep
        uses: actions/checkout@v4
      - name: setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{matrix.version}}
      - name: lint
        run: mvn checkstyle:checkstyle
      - name: upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: target/